doctrine_migrations:
    migrations_paths:
        'PayrollReport\Modules\Department\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Department/Infrastructure/Persistence'
        'PayrollReport\Modules\Report\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Report/Infrastructure/Persistence'
    enable_profiler: '%kernel.debug%'