framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        default_bus: query.bus
        buses:
            query.bus: ~
            command.bus: ~

        routing:
