version: '3.8'

services:
    db:
        container_name: payroll_report-db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_USER: ${MYSQL_DATABASE_USER}
            MYSQL_PASSWORD: ${MYSQL_DATABASE_USER_PASSWORD}
        ports:
            -   '4306:3306'
        volumes:
            -   ./mysql:/var/lib/mysql

    php:
        container_name: payroll_report-php
        build:
            context: ./docker/php
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        ports:
            -   '9000:9000'
        volumes:
            -   ./:/var/www/payroll_report
        depends_on:
            -   db

    nginx:
        container_name: payroll_report-nginx
        image: nginx:1.19.2-alpine
        ports:
            -   '8080:80'
        volumes:
            -   ./:/var/www/payroll_report
            -   ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            -   db
